### ISSUE TITLE
Globally installed sw-cli throws unhelpful errors

### ISSUE THREAD

**Issue by StephenFluin** [GoogleChrome/sw-helpers#360]
**Library Affected**:
sw-cli

**Browser & Platform**:
NodeJS v7.1.0
NPM 3.10.9
MacOS 10.12.3

**Issue or Feature Request Description**:
I ran `npm install -g sw-cli` and then ran `sw-cli generate-sw`

Observed behavior:
```
$ sw-cli
module.js:474
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/stephenfluin/.nvm/versions/node/v7.1.0/lib/node_modules/sw-cli/node_modules/sw-build/build/lib/utils/get-file-details.js:1:76)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

Expected behavior:
Either it to work, or to throw a helpful error message about not installing sw-cli globally.

**Comment by StephenFluin** [comment]
This is probably a duplicate of https://github.com/GoogleChrome/sw-helpers/issues/325
