### ISSUE TITLE
learna bootstrap needs to be run following npm install

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#457]
Following a fresh

```sh
git clone https://github.com/googlechrome/sw-helpers
cd sw-helpers
npm install
gulp lint:repo
```

on OS X, I get the following:

```sh
[17:35:58] Using gulpfile /private/tmp/sw-helpers/gulpfile.js
[17:35:58] Starting 'lint:repo'...
/private/tmp/sw-helpers/node_modules/eslint/lib/config.js:170
            throw noConfigError;
            ^

Error: No ESLint configuration found.
    at getLocalConfig (/private/tmp/sw-helpers/node_modules/eslint/lib/config.js:162:35)
    at Config.getConfig (/private/tmp/sw-helpers/node_modules/eslint/lib/config.js:260:26)
    at processText (/private/tmp/sw-helpers/node_modules/eslint/lib/cli-engine.js:224:33)
    at CLIEngine.executeOnText (/private/tmp/sw-helpers/node_modules/eslint/lib/cli-engine.js:754:26)
    at verify (/private/tmp/sw-helpers/node_modules/gulp-eslint/index.js:20:25)
    at Transform.util.transform [as _transform] (/private/tmp/sw-helpers/node_modules/gulp-eslint/index.js:70:17)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
```

`gulp lint:repo` is run as part of `gulp test`, and `gulp test` needs to pass to do things like push via `lerna`.

**Comment by jeffposnick** [comment]
It looks like it succeeds when `lerna bootstrap --concurrency 1` is run following the `npm install`.

Maybe something to document as part of a "guide to contributing".
