### ISSUE TITLE
npm run serve fails with a missing script error, though still listed in package.json

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/sw-helpers#471]
Console Output:

```
npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/jmedley/Homebrew/Cellar/node/7.4.0/bin/node" "/Users/jmedley/Homebrew/bin/npm" "run" "serve"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! missing script: serve
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jmedley/Documents/tools/workbox/npm-debug.log
```

npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/jmedley/Homebrew/Cellar/node/7.4.0/bin/node',
1 verbose cli   '/Users/jmedley/Homebrew/bin/npm',
1 verbose cli   'run',
1 verbose cli   'serve' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose stack Error: missing script: serve
4 verbose stack     at run (/Users/jmedley/Homebrew/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /Users/jmedley/Homebrew/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /Users/jmedley/Homebrew/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/Users/jmedley/Homebrew/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/Users/jmedley/Homebrew/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/Users/jmedley/Homebrew/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /Users/jmedley/Homebrew/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
4 verbose stack     at /Users/jmedley/Homebrew/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:426:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
5 verbose cwd /Users/jmedley/Documents/tools/workbox
6 error Darwin 16.5.0
7 error argv "/Users/jmedley/Homebrew/Cellar/node/7.4.0/bin/node" "/Users/jmedley/Homebrew/bin/npm" "run" "serve"
8 error node v7.4.0
9 error npm  v4.0.5
10 error missing script: serve
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

**Comment by jeffposnick** [comment]
It was renamed to `local-docs` in https://github.com/GoogleChrome/sw-helpers/pull/467/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R7, because `npm run serve` didn't fully describe what it did.

I'm not sure what you mean when you say that it's still listed in `package.json`, since it was renamed in that PR.
