### ISSUE TITLE
Resolve incompatibility with latest selenium-webdriver

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#5]
`selenium-webdriver` v2.52.0 was unable to automatically detect the local ChromeDriver instance I had on the `PATH` in my development environment. Rather than debug that incompatibility, I locked down the version to v2.52.0 via a [`npm-shrinkwrap.json`](https://github.com/GoogleChrome/sw-helpers/blob/991a5f3999065ddd540610725736d654c9fa5280/npm-shrinkwrap.json).

Given more time, I should get to the root of the issue and file a bug against `selenium-webdriver` if it turns out to be an issue on their end.

**Comment by jeffposnick** [comment]
For the record, the specific error I get is

```sh
     TypeError: Path must be a string. Received -1
      at assertPath (path.js:7:11)
      at Object.join (path.js:1213:7)
      at Object.exports.findInPath.opt_checkCwd [as findInPath] (node_modules/selenium-webdriver/io/index.js:232:28)
      at new ServiceBuilder (node_modules/selenium-webdriver/chrome.js:183:29)
      at getDefaultService (node_modules/selenium-webdriver/chrome.js:362:22)
      at Driver (node_modules/selenium-webdriver/chrome.js:771:34)
      at Builder.build (node_modules/selenium-webdriver/builder.js:464:16)
      at ChromeWebDriverBrowser.getSeleniumDriver (node_modules/sw-testing-helpers/node/webdriver-browser/web-driver-browser.js:161:8)
      at Context.<anonymous> (automated-suite.js:72:24)
```
