### ISSUE TITLE
Can't run gulp documentation

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/sw-helpers#507]
Throws an error with the following output:

```
module.js:472
    throw err;
    ^

Error: Cannot find module 'rollup-plugin-replace'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jmedley/Documents/tools/workbox/utils/build.js:24:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by jeffposnick** [comment]
It's a fairly new dependency, added to the top-level [`package.json`](https://github.com/GoogleChrome/sw-helpers/blob/master/package.json#L63)

Running `npm install` from the repo's root should install it.

**Comment by jpmedley** [comment]
I don't think it's that. `npm install` gives me

`gulp-spawn-mocha@3.1.0 requires a peer of istanbul@^0.4.3 but none was installed.` 

and 

`UNMET PEER DEPENDENCY istanbul@^0.4.3`

So I tried to install istanbul and got:

` Registry returned 404 for GET on https://registry.npmjs.org/instanbul`

Why they changed it I can't say. People just like it better that way.

**Comment by jpmedley** [comment]
I deleted `node_modules` and reran `npm install`. The problem went away.
