### ISSUE TITLE
Failing Travis CI builds

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/sw-helpers#88]
See https://travis-ci.org/GoogleChrome/sw-helpers/builds/183653927

The errors include:

```
  1) sw-lib Tests sw-lib Tests in Google Chrome Dev should pass all browser based unit tests:
     Error: Failing tests
      at assistantDriver.getSeleniumDriver.then.then.then (packages/sw-lib/test/automated-test-suite.js:93:19)
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1366:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2970:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2953:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2813:27)
      at node_modules/selenium-webdriver/lib/promise.js:676:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
{ [Error: Mocha exited with code 1]
  message: 'Mocha exited with code 1',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-spawn-mocha',
  __safety: { toString: [Function: bound ] } }
```

and

```
  1) sw-precaching Browser Tests should pass all browser based unit tests in  Google Chrome Dev:
     Error: Issues in Google Chrome Dev.
Google Chrome Dev had 1 test failures.
------------------------------------------------
[Failed Test 1]
    - sw-precaching Test Revisioned Caching > should cache and fetch files
        Cannot read property 'should' of undefined
------------------------------------------------
      at assistantDriver.getSeleniumDriver.then.then.then (packages/sw-precaching/test/automated-test-suite.js:74:17)
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1366:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:2970:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:2953:27)
      at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2813:27)
      at node_modules/selenium-webdriver/lib/promise.js:676:7
      at process._tickCallback (internal/process/next_tick.js:103:7)
{ [Error: Mocha exited with code 1]
  message: 'Mocha exited with code 1',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-spawn-mocha',
  __safety: { toString: [Function: bound ] } }
```

**Comment by gauntface** [comment]
So with the refactor of precaching merged, this has some changes that *should* help with the builds.

Will leave this issue open for now, but if I see a couple of PR's start landing without Travis oddities, I'll close this bug.

**Comment by addyosmani** [comment]
I'm unsure if it would help at all, but Nolan published a Travis restart helper this weekend https://gist.github.com/nolanlawson/7b7961b49b75e406dc7090ce6217bb5f

**Comment by gauntface** [comment]
I think I've made things a bit more stable now.

Now all tests use the same ports for serving content and splitting things up has helped a bit.

Happy for me to close this?

**Comment by jeffposnick** [comment]
👍
